version: "3"

networks:
  default:
    ipam:
      config:
        - subnet: 10.202.202.0/24

services:
  coredns:
    container_name: coredns
    build: ../coredns-docker/
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - "../config/coredns/:/etc/coredns:ro"
      - "../config/coredns/zones:/etc/coredns/zones:ro"
    restart: unless-stopped
    read_only: true
    networks:
      default:
        ipv4_address: 10.202.202.2

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: "test12345"
      ServerIP: 10.42.0.2
      DNS1: 10.202.202.4#5053
      DNS2: 10.202.202.4#5053
    volumes:
      - "../config/pihole/pihole/:/etc/pihole/"
      - "../config/pihole/dnsmasq/:/etc/dnsmasq.d/"
    dns:
      - 127.0.0.1
      - 8.8.8.8
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 10.202.202.3

  cloudflared:
    image: crazymax/cloudflared:latest
    container_name: cloudflared
    environment:
      - "TZ=Europe/Berlin"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
    restart: unless-stopped
    read_only: true
    networks:
      default:
        ipv4_address: 10.202.202.4
